"use client";

import { ArrowRight,CheckCircle,Desktop,DeviceMobile,FileText,FloppyDisk,GitBranch,PaperPlaneTilt,Translate,WarningCircle } from "@phosphor-icons/react";
import { AdminPageDraftCommandSchema,type AdminContentManagementView,type AdminContentPublicationView,type AdminPageContent } from "@tikdd/admin-contracts";
import { useEffect,useMemo,useState } from "react";

const stateLabel:Record<string,string>={missing:"缺失",fallback:"回退",draft:"草稿",ready:"就绪",published:"已发布",archived:"已归档"};
function fallbackChain(view:AdminContentManagementView,locale:string){const chain=[locale];let current=view.locales.find(item=>item.locale===locale)?.effective;const seen=new Set(chain);while(current?.fallbackLocale&&!seen.has(current.fallbackLocale)){chain.push(current.fallbackLocale);seen.add(current.fallbackLocale);current=view.locales.find(item=>item.locale===current?.fallbackLocale)?.effective;}return chain;}
function contentTitle(content:AdminPageContent|undefined){if(!content)return"尚未创建内容";if(content.template==="homepage")return content.heroTitle;return content.title;}
function contentSummary(content:AdminPageContent|undefined){if(!content)return"从代码模板创建草稿后，这里会显示真实结构预览。";if(content.template==="homepage")return content.heroSubtitle;if(content.template==="platform")return content.introduction;if(content.template==="legal")return content.summary;return content.introduction;}
function buildContent(template:AdminPageContent["template"],title:string,summary:string):AdminPageContent{switch(template){case"homepage":return{template,heroTitle:title,heroSubtitle:summary,inputLabel:"视频页面链接",inputPlaceholder:"粘贴公开视频页面链接",primaryActionLabel:"解析视频",supportedPlatformsTitle:"支持的平台",howItWorksTitle:"如何使用",howItWorksSteps:[{title:"粘贴链接",description:"提交公开的视频页面地址。"},{title:"选择格式",description:"解析完成后选择可用格式。"}],faqTitle:"常见问题",faqItems:[{question:"TikDD 会保存媒体吗？",answerMarkdown:"TikDD 只处理完成任务所需的数据。"}]};case"platform":return{template,eyebrow:"SUPPORTED PLATFORM",title,introduction:summary,limitationsMarkdown:"仅支持公开且允许访问的内容。",howToSteps:[{title:"复制链接",description:"从平台复制公开视频页面地址。"},{title:"开始解析",description:"返回可用的下载候选。"}],faqItems:[]};case"faq":return{template,title,introduction:summary,items:[{question:"如何开始？",answerMarkdown:"粘贴公开视频页面链接并提交。"}]};case"legal":return{template,title,summary,sections:[{id:"overview",heading:"说明",bodyMarkdown:summary}]};default:return{template:"guide",title,introduction:summary,sections:[{id:"start",heading:"开始使用",bodyMarkdown:summary}]};}}

export function ContentManagement({view,publication,csrfToken,onReload}:{view:AdminContentManagementView|null;publication:AdminContentPublicationView|null;csrfToken:string|null;onReload:()=>void}){
  const [selectedLocale,setSelectedLocale]=useState(view?.locales[0]?.locale??"en");const [selectedPage,setSelectedPage]=useState("page_home");const [preview,setPreview]=useState<"desktop"|"mobile">("desktop");const [reason,setReason]=useState("Publish the reviewed structured content snapshot.");const [confirmation,setConfirmation]=useState("");const [message,setMessage]=useState("");const [title,setTitle]=useState("");const [summary,setSummary]=useState("");const [fieldErrors,setFieldErrors]=useState<string[]>([]);
  const selected=view?.locales.find(item=>item.locale===selectedLocale)??view?.locales[0];const definition=view?.definitions.find(item=>item.pageId===selectedPage)??view?.definitions[0];const revision=view?.pages.find(page=>page.pageId===definition?.pageId&&page.locale===selected?.locale);const chain=useMemo(()=>view&&selected?fallbackChain(view,selected.locale):[],[view,selected]);
  useEffect(()=>{setTitle(contentTitle(revision?.content));setSummary(contentSummary(revision?.content));setFieldErrors([]);},[revision?.revision,definition?.pageId,selected?.locale]);
  if(!view)return <section className="content-management panel" id="publishing"><WarningCircle size={26}/><h2>内容模型暂不可用</h2><p>恢复 Admin API 后再编辑或发布；不会使用缓存草稿推断成功。</p></section>;
  const enabled=view.locales.filter(({effective})=>effective.enabled);const send=async(payload:unknown)=>{const response=await fetch("/api/admin/snapshot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setMessage(response.ok?"操作已由权威状态确认。":"操作未完成，请刷新版本后重试。");if(response.ok)onReload();};const savePage=async(state:"draft"|"ready")=>{if(!csrfToken||!definition||!selected)return;const localPath=revision?.seo.localPath??(definition.pageType==="homepage"?"/":`/${definition.pageId.replace("page_","").replaceAll("_","-")}`);const searchDescription=summary.length>=40?summary:`${summary} TikDD 仅解析公开媒体页面，并以统一结果展示经过验证的可用格式与受控交付选项。`;const parsed=AdminPageDraftCommandSchema.safeParse({pageId:definition.pageId,locale:selected.locale,pageType:definition.pageType,platform:definition.platform,state,content:buildContent(definition.pageType,title,summary),seo:{localPath,searchTitle:(title.length>=10?title:`${title} | TikDD`).slice(0,70),searchDescription:searchDescription.slice(0,180),socialTitle:null,socialDescription:null,socialImageAssetId:null,indexable:false,includeInSitemap:false,redirectFrom:[]},expectedRevision:revision?.revision??null,reason:"Update structured page content from the proofing desk.",confirmation:`${definition.pageId}/${selected.locale}`,idempotencyKey:crypto.randomUUID().replaceAll("-","")});if(!parsed.success){setFieldErrors(parsed.error.issues.map(issue=>`${issue.path.join(".")}: ${issue.message}`));setMessage("请先修正字段错误。");return;}setFieldErrors([]);setMessage("保存中…");await send({action:"page_draft",csrfToken,command:parsed.data});};const publish=async(action:"content_publish"|"content_rollback"|"content_retry",extra:Record<string,unknown>={})=>{if(!publication||!csrfToken)return;setMessage("处理中…");const command={deployment:publication.deployment,expectedRevision:publication.currentRevision,reason,confirmation,idempotencyKey:crypto.randomUUID().replaceAll("-",""),...extra};await send({action,csrfToken,command});};
  return <section className="content-management" id="publishing">
    <header className="content-heading"><div><p className="eyebrow">CONTENT / PROOFING DESK</p><h2>结构化内容校样台</h2><p>左侧编辑代码定义的字段，中间使用真实模板结构预览，发布时只提升一个完整不可变快照。</p></div><div className="content-score"><strong>{publication?.readyPageCount??0}</strong><span>个页面草稿已就绪</span></div></header>
    <div className="publication-film panel"><div className="film-step ready"><span>01</span><strong>结构校验</strong><small>固定模板 · Safe Markdown</small></div><ArrowRight/><div className={`film-step ${publication?.blockers.length===0?"ready":"blocked"}`}><span>02</span><strong>完整快照</strong><small>{publication?.blockers.length??0} 个阻塞</small></div><ArrowRight/><div className={`film-step state-${publication?.propagationState??"idle"}`}><span>03</span><strong>路径确认</strong><small>{publication?.propagationState??"idle"}</small></div><ArrowRight/><div className="film-step"><span>04</span><strong>公共读取</strong><small>12.9 接入快照加载器</small></div></div>
    <div className="proofing-shell panel">
      <aside className="proofing-index"><div className="mini-heading"><Translate size={16}/><strong>Locale / 页面</strong></div><select value={selected?.locale} onChange={event=>setSelectedLocale(event.target.value)}>{view.locales.map(item=><option key={item.locale} value={item.locale}>{item.effective.displayName} · {item.locale}</option>)}</select>{view.definitions.map(item=><button className={item.pageId===definition?.pageId?"selected":""} key={item.pageId} onClick={()=>setSelectedPage(item.pageId)}><FileText size={15}/><span><strong>{item.label}</strong><small>{item.pageType} · v{item.templateVersion}</small></span><b>{stateLabel[view.coverage.find(cell=>cell.pageId===item.pageId&&cell.locale===selected?.locale)?.status??"missing"]}</b></button>)}</aside>
      <div className="proofing-workbench">
        <div className="fallback-ribbon"><span><GitBranch size={18}/></span><div><small>当前回退链</small><div>{chain.map((tag,index)=><span key={tag}><b>{tag}</b>{index<chain.length-1?<ArrowRight size={13}/>:null}</span>)}</div></div><em>{selected?.effective.direction.toUpperCase()}</em></div>
        <div className="editor-preview-grid"><section className="structured-editor"><header><div><small>STRUCTURED FIELDS</small><strong>{definition?.label}</strong></div><span>{revision?`r${revision.revision}`:"NEW"}</span></header><label>主标题<input aria-invalid={fieldErrors.some(error=>/content\.(heroTitle|title)/.test(error))} value={title} onChange={event=>setTitle(event.target.value)}/></label><label>摘要<textarea aria-invalid={fieldErrors.some(error=>/content\.(heroSubtitle|introduction|summary)/.test(error))} value={summary} onChange={event=>setSummary(event.target.value)}/></label><div className="field-grid"><label>页面类型<input value={definition?.pageType??""} readOnly/></label><label>本地路径<input value={revision?.seo.localPath??"/"} readOnly/></label></div>{fieldErrors.length?<div className="validation-summary" role="alert"><strong>请修正 {fieldErrors.length} 个字段问题</strong><ul>{fieldErrors.slice(0,5).map(error=><li key={error}>{error}</li>)}</ul></div>:null}<div className="editor-note"><FloppyDisk size={17}/><p>字段由代码模板约束，不接受任意 HTML 或组件。保存“就绪”后才会进入完整快照检查。</p></div><div className="editor-actions"><button onClick={()=>void savePage("draft")}>保存草稿</button><button className="primary" onClick={()=>void savePage("ready")}>保存并标记就绪</button></div></section>
        <section className={`template-preview preview-${preview}`} dir={selected?.effective.direction}><header><div><small>REAL TEMPLATE PREVIEW</small><strong>{selected?.locale} · {definition?.pageType}</strong></div><div><button className={preview==="desktop"?"active":""} onClick={()=>setPreview("desktop")} aria-label="桌面预览"><Desktop size={16}/></button><button className={preview==="mobile"?"active":""} onClick={()=>setPreview("mobile")} aria-label="移动预览"><DeviceMobile size={16}/></button></div></header><div className="preview-canvas"><nav><b>Tik<span>DD</span></b><i>{selected?.effective.displayName}</i></nav><main><small>{definition?.pageType.toUpperCase()}</small><h3>{title}</h3><p>{summary}</p><div className="preview-input"><span>{revision?.content.template==="homepage"?revision.content.inputPlaceholder:"Structured page content"}</span><b>{revision?.content.template==="homepage"?revision.content.primaryActionLabel:"TikDD"}</b></div></main></div></section></div>
        <div className="revision-strip"><div><small>DRAFT → PUBLISHED DIFF</small><strong>{publication?.diff.length??0} 个变更 · {publication?.affectedPaths.length??0} 条受影响路径</strong></div><div className="diff-list">{publication?.diff.slice(0,4).map(item=><span key={item.targetId}><b>{item.change}</b>{item.targetId}</span>)}{!publication?.diff.length?<span>没有待发布差异</span>:null}</div></div>
        <div className="publication-command"><div><label>发布理由<textarea value={reason} onChange={event=>setReason(event.target.value)}/></label><label>输入部署 ID <code>{publication?.deployment}</code><input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label></div><div className="publish-summary"><p>{publication?.blockers.length?`阻塞：${publication.blockers.join("、")}`:"所有完整性检查通过，可提升为一个不可变快照。"}</p><div className="command-actions"><button className="primary" disabled={!publication||publication.blockers.length>0||confirmation!==publication.deployment} onClick={()=>void publish("content_publish")}><PaperPlaneTilt size={15}/>发布快照</button>{publication?.propagationState==="propagation_failed"&&publication.pendingSnapshotId?<button onClick={()=>void publish("content_retry",{snapshotId:publication.pendingSnapshotId})}>重试确认</button>:null}{publication?.rollbackCandidates[1]?<button className="quiet" onClick={()=>void publish("content_rollback",{targetRevision:publication.rollbackCandidates[1]!.revision})}>回滚到 r{publication.rollbackCandidates[1]!.revision}</button>:null}</div>{message?<span className="command-message">{message}</span>:null}</div></div>
      </div>
    </div>
    <div className="coverage-matrix compact-matrix"><table><thead><tr><th>代码模板</th>{enabled.map(item=><th key={item.locale}>{item.locale}</th>)}</tr></thead><tbody>{view.definitions.slice(0,8).map(item=><tr key={item.pageId}><th><strong>{item.label}</strong></th>{enabled.map(locale=>{const cell=view.coverage.find(candidate=>candidate.pageId===item.pageId&&candidate.locale===locale.locale);return <td key={locale.locale}><span className={`matrix-cell state-${cell?.status??"missing"}`}>{["ready","published"].includes(cell?.status??"")?<CheckCircle size={16}/>:cell?.status==="fallback"?<GitBranch size={15}/>:<WarningCircle size={15}/>}<b>{stateLabel[cell?.status??"missing"]}</b></span></td>})}</tr>)}</tbody></table></div>
  </section>;
}
