"use client";

import { CheckCircle,Globe,LinkSimple,ShareNetwork,WarningCircle } from "@phosphor-icons/react";
import { AdminPageDraftCommandSchema,type AdminContentManagementView,type AdminSeoTechnicalView } from "@tikdd/admin-contracts";
import { useEffect,useMemo,useState } from "react";

export function SeoWorkbench({view,technical,csrfToken,onReload}:{view:AdminContentManagementView|null;technical:AdminSeoTechnicalView|null;csrfToken:string|null;onReload:()=>void}){
  const [key,setKey]=useState("");const [path,setPath]=useState("/");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [socialTitle,setSocialTitle]=useState("");const [socialDescription,setSocialDescription]=useState("");const [redirects,setRedirects]=useState("");const [indexable,setIndexable]=useState(false);const [sitemap,setSitemap]=useState(false);const [errors,setErrors]=useState<string[]>([]);const [message,setMessage]=useState("");
  const pages=view?.pages.filter(page=>["draft","ready","published"].includes(page.state))??[];const selected=pages.find(page=>`${page.pageId}/${page.locale}`===key)??pages[0];const passport=technical?.passports.find(item=>item.pageId===selected?.pageId&&item.locale===selected?.locale);
  useEffect(()=>{if(!selected)return;setKey(`${selected.pageId}/${selected.locale}`);setPath(selected.seo.localPath);setTitle(selected.seo.searchTitle);setDescription(selected.seo.searchDescription);setSocialTitle(selected.seo.socialTitle??"");setSocialDescription(selected.seo.socialDescription??"");setRedirects(selected.seo.redirectFrom.join("\n"));setIndexable(selected.seo.indexable);setSitemap(selected.seo.includeInSitemap);setErrors([]);},[selected?.pageId,selected?.locale,selected?.revision]);
  const redirectFrom=useMemo(()=>redirects.split(/\r?\n/).map(item=>item.trim()).filter(Boolean),[redirects]);
  if(!view)return null;
  if(!pages.length)return <section className="seo-workbench" id="seo-readiness"><header className="content-heading"><div><p className="eyebrow">SEO / INDEX PASSPORT</p><h2>搜索索引护照</h2><p>编辑公众可见的搜索与社交字段；Canonical、hreflang、Sitemap、结构化数据和私有路由保护由系统派生。</p></div><div className="content-score"><strong>0</strong><span>个技术发布阻塞</span></div></header><div className="seo-empty panel"><WarningCircle size={30}/><div><h3>尚无可配置页面</h3><p>先在内容校样台创建页面草稿，再回到这里配置搜索与分享信息。</p></div></div></section>;
  const save=async()=>{if(!selected||!csrfToken)return;const command={pageId:selected.pageId,locale:selected.locale,pageType:selected.pageType,platform:selected.platform,state:selected.state==="ready"?"ready" as const:"draft" as const,content:selected.content,seo:{localPath:path,searchTitle:title,searchDescription:description,socialTitle:socialTitle||null,socialDescription:socialDescription||null,socialImageAssetId:selected.seo.socialImageAssetId,indexable,includeInSitemap:sitemap,redirectFrom},expectedRevision:selected.revision,reason:"Update localized technical SEO from the index passport.",confirmation:`${selected.pageId}/${selected.locale}`,idempotencyKey:crypto.randomUUID().replaceAll("-","")};const parsed=AdminPageDraftCommandSchema.safeParse(command);if(!parsed.success){setErrors(parsed.error.issues.map(issue=>`${issue.path.join(".")}: ${issue.message}`));return;}setErrors([]);setMessage("保存中…");const response=await fetch("/api/admin/snapshot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"page_draft",csrfToken,command:parsed.data})});setMessage(response.ok?"SEO 草稿已保存。":"SEO 草稿保存失败，请刷新版本。");if(response.ok)onReload();};
  return <section className="seo-workbench" id="seo-readiness"><header className="content-heading"><div><p className="eyebrow">SEO / INDEX PASSPORT</p><h2>搜索索引护照</h2><p>编辑公众可见的搜索与社交字段；Canonical、hreflang、Sitemap、结构化数据和私有路由保护由系统派生。</p></div><div className="content-score"><strong>{technical?.blockerCount??0}</strong><span>个技术发布阻塞</span></div></header>
    <div className="seo-passport panel"><aside><div className="mini-heading"><Globe size={16}/><strong>页面 / 语言</strong></div><select value={selected?`${selected.pageId}/${selected.locale}`:""} onChange={event=>setKey(event.target.value)}>{pages.map(page=><option key={`${page.pageId}/${page.locale}`} value={`${page.pageId}/${page.locale}`}>{page.pageId.replace("page_","")} · {page.locale}</option>)}</select><div className={`passport-stamp ${passport?.indexableEligible?"approved":"blocked"}`}>{passport?.indexableEligible?<CheckCircle size={28} weight="fill"/>:<WarningCircle size={28}/>}<strong>{passport?.indexableEligible?"INDEX ELIGIBLE":"NOT ELIGIBLE"}</strong><small>{passport?.structuredDataTemplate??"WebPage"}</small></div><dl><dt>Canonical</dt><dd>{passport?.canonicalPath??"—"}</dd><dt>hreflang</dt><dd>{passport?.hreflang.map(item=>item.locale).join(" · ")||"—"}</dd><dt>Sitemap</dt><dd>{passport?.sitemapEligible?"included":"excluded"}</dd></dl></aside>
      <div className="seo-editor"><section><header><LinkSimple/><div><small>SEARCH FIELDS</small><strong>本地路径与搜索摘要</strong></div></header><label>本地路径<input value={path} onChange={event=>setPath(event.target.value)}/></label><label>搜索标题 <span>{title.length}/70</span><input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>搜索描述 <span>{description.length}/180</span><textarea value={description} onChange={event=>setDescription(event.target.value)}/></label><div className="seo-flags"><label><input type="checkbox" checked={indexable} onChange={event=>setIndexable(event.target.checked)}/>允许索引</label><label><input type="checkbox" checked={sitemap} onChange={event=>setSitemap(event.target.checked)}/>加入 Sitemap</label></div><label>旧路径重定向（每行一个）<textarea value={redirects} onChange={event=>setRedirects(event.target.value)} placeholder="/old-path"/></label></section>
        <section><header><ShareNetwork/><div><small>SOCIAL + PREVIEW</small><strong>搜索与分享卡片</strong></div></header><label>社交标题<input value={socialTitle} onChange={event=>setSocialTitle(event.target.value)}/></label><label>社交描述<textarea value={socialDescription} onChange={event=>setSocialDescription(event.target.value)}/></label><div className="serp-preview"><small>{passport?.canonicalPath??`/${selected?.locale??"en"}`}</small><h3>{title||"搜索标题预览"}</h3><p>{description||"搜索结果描述将在这里预览。"}</p></div><div className="social-preview"><span>TikDD</span><strong>{socialTitle||title||"社交卡片标题"}</strong><p>{socialDescription||description||"社交卡片描述"}</p></div></section>
        <footer>{errors.length?<div className="validation-summary" role="alert"><strong>请修正 {errors.length} 个字段问题</strong><ul>{errors.slice(0,6).map(error=><li key={error}>{error}</li>)}</ul></div>:passport?.blockers.length?<div className="seo-blockers"><strong>技术阻塞</strong>{passport.blockers.map(item=><span key={item}>{item}</span>)}</div>:<p><CheckCircle/> 当前页面没有技术 SEO 阻塞。</p>}<button className="primary" onClick={()=>void save()}>保存 SEO 草稿</button>{message?<small>{message}</small>:null}</footer>
      </div></div>
  </section>;
}
