"use client";

import { ArrowClockwise,Cloud,Database,GlobeHemisphereWest,HardDrives,Key,ShieldCheck,WarningCircle } from "@phosphor-icons/react";
import type { AdminContentManagementView,AdminSettingsRecoveryView } from "@tikdd/admin-contracts";
import { useEffect,useState } from "react";

const stateLabel:Record<string,string>={ready:"就绪",degraded:"需关注",unavailable:"不可用",healthy:"健康",stale:"过期",configured:"已配置",missing:"缺失",propagated:"已确认",propagating:"确认中",propagation_failed:"确认失败",idle:"空闲"};
const isCanonicalLocaleTag=(value:string)=>{try{return value.length>=2&&value.length<=35&&/^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/.test(value)&&Intl.getCanonicalLocales(value)[0]===value;}catch{return false;}};

export function SettingsRecovery({view,content,csrfToken,onReload}:{view:AdminSettingsRecoveryView|null;content:AdminContentManagementView|null;csrfToken:string|null;onReload:()=>void}){
  const [locale,setLocale]=useState(view?.publicationDefaults.defaultLocale??"en");const identity=view?.siteIdentity.find(item=>item.locale===locale)??view?.siteIdentity[0];const localeSetting=view?.locales.find(item=>item.locale===locale)??view?.locales[0];
  const shared=content?.sharedContent.find(item=>item.locale===identity?.locale);const [siteName,setSiteName]=useState(identity?.siteName??"TikDD");const [tagline,setTagline]=useState(identity?.footerTagline??"");const [socialTitle,setSocialTitle]=useState(identity?.defaultSocial.title??"");const [socialDescription,setSocialDescription]=useState(identity?.defaultSocial.description??"");const [socialImageAssetId,setSocialImageAssetId]=useState(identity?.defaultSocial.imageAssetId??"");const [reason,setReason]=useState("Update bounded site settings.");const [confirmation,setConfirmation]=useState("");const [message,setMessage]=useState("");
  const [direction,setDirection]=useState<"ltr"|"rtl">(localeSetting?.direction??"ltr");const [fallbackLocale,setFallbackLocale]=useState(localeSetting?.fallbackLocale??"");const [enabled,setEnabled]=useState(localeSetting?.enabled??true);const [isDefault,setIsDefault]=useState(localeSetting?.isDefault??false);
  const [newLocale,setNewLocale]=useState("");const [newLocaleName,setNewLocaleName]=useState("");const [newLocaleDirection,setNewLocaleDirection]=useState<"ltr"|"rtl">("ltr");const [newLocaleFallback,setNewLocaleFallback]=useState(view?.publicationDefaults.defaultLocale??"");
  useEffect(()=>{setSiteName(identity?.siteName??"TikDD");setTagline(identity?.footerTagline??"");setSocialTitle(identity?.defaultSocial.title??"");setSocialDescription(identity?.defaultSocial.description??"");setSocialImageAssetId(identity?.defaultSocial.imageAssetId??"");},[identity?.locale,identity?.revision]);
  useEffect(()=>{setDirection(localeSetting?.direction??"ltr");setFallbackLocale(localeSetting?.fallbackLocale??"");setEnabled(localeSetting?.enabled??true);setIsDefault(localeSetting?.isDefault??false);},[localeSetting?.locale,localeSetting?.revision]);
  if(!view)return <section className="settings-recovery" id="runtime"><header><p className="eyebrow">SYSTEM / SETTINGS</p><h2>设置与恢复</h2></header><div className="panel settings-empty"><WarningCircle size={26}/><strong>设置投影不可用</strong><p>不会使用缓存值或环境推断替代权威状态。</p></div></section>;
  const send=async(payload:unknown)=>{setMessage("处理中…");const response=await fetch("/api/admin/snapshot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setMessage(response.ok?"命令已由权威状态确认。":"命令未完成，请刷新版本后重试。");if(response.ok)onReload();};
  const socialImageAssetIdValid=!socialImageAssetId||/^asset_[a-z0-9]+(?:[._-][a-z0-9]+)*$/.test(socialImageAssetId);
  const newLocaleValid=isCanonicalLocaleTag(newLocale)&&!view.locales.some(item=>item.locale===newLocale);
  const saveIdentity=()=>{if(!csrfToken||!identity||!socialImageAssetIdValid)return;void send({action:"shared_draft",csrfToken,command:{locale:identity.locale,state:"ready",content:{siteName,navigationLabel:identity.navigationLabel,footerTagline:tagline,legalNoticeMarkdown:identity.legalNoticeMarkdown,defaultSocialTitle:socialTitle||null,defaultSocialDescription:socialDescription||null,defaultSocialImageAssetId:socialImageAssetId||null},expectedRevision:shared?.revision??null,reason,confirmation:identity.locale,idempotencyKey:crypto.randomUUID().replaceAll("-","")}});};
  const saveLocale=()=>{if(!csrfToken||!localeSetting)return;void send({action:"locale_draft",csrfToken,command:{locale:localeSetting.locale,displayName:localeSetting.displayName,direction,fallbackLocale:isDefault?null:fallbackLocale||null,enabled,isDefault,state:"ready",expectedRevision:localeSetting.revision,reason,confirmation:localeSetting.locale,idempotencyKey:crypto.randomUUID().replaceAll("-","")}});};
  const createLocale=()=>{if(!csrfToken||!newLocaleValid||!newLocaleName.trim())return;void send({action:"locale_draft",csrfToken,command:{locale:newLocale,displayName:newLocaleName,direction:newLocaleDirection,fallbackLocale:newLocaleFallback||null,enabled:true,isDefault:false,state:"draft",expectedRevision:null,reason,confirmation:newLocale,idempotencyKey:crypto.randomUUID().replaceAll("-","")}});};
  const recover=(action:"recovery_rebuild"|"recovery_invalidate")=>{const target=action==="recovery_rebuild"?view.recovery.rebuildSnapshot.sourceSnapshotId:view.recovery.invalidateContentCache.snapshotId;if(!csrfToken||!target||confirmation!==view.infrastructure.deployment)return;void send({action,csrfToken,command:{deployment:view.infrastructure.deployment,expectedRevision:view.infrastructure.snapshot.latestRevision,reason,confirmation, idempotencyKey:crypto.randomUUID().replaceAll("-",""),...(action==="recovery_rebuild"?{sourceSnapshotId:target}:{snapshotId:target})}});};
  return <section className="settings-recovery" id="runtime">
    <header className="content-heading"><div><p className="eyebrow">SYSTEM / BOUNDED SETTINGS</p><h2>站点设置与受限恢复</h2><p>日常配置落入既有版本链；运行信息只读，凭据只显示是否已配置，恢复仅作用于已知快照及其已记录路径。</p></div><span className={`settings-state state-${view.infrastructure.state}`}><ShieldCheck size={16}/>{stateLabel[view.infrastructure.state]}</span></header>
    <div className="settings-grid">
      <section className="panel settings-editor"><header><div><small>SITE IDENTITY / LOCALE</small><strong>站点身份与默认社交元数据</strong></div><select value={identity?.locale} onChange={event=>setLocale(event.target.value)}>{view.locales.map(item=><option key={item.locale} value={item.locale}>{item.displayName} · {item.locale}</option>)}</select></header>{identity?<><div className="settings-fields"><label>站点名称<input value={siteName} onChange={event=>setSiteName(event.target.value)} maxLength={80}/></label><label>页脚标语<input value={tagline} onChange={event=>setTagline(event.target.value)} maxLength={240}/></label><label>默认社交标题<input value={socialTitle} onChange={event=>setSocialTitle(event.target.value)} maxLength={100} placeholder="页面未单独配置时使用"/></label><label>默认社交描述<textarea value={socialDescription} onChange={event=>setSocialDescription(event.target.value)} maxLength={240}/></label><label className="settings-wide">默认社交图片资产 ID<input value={socialImageAssetId} onChange={event=>setSocialImageAssetId(event.target.value)} maxLength={100} aria-invalid={!socialImageAssetIdValid} placeholder="仅引用已批准的 asset_* 媒体资产，可留空"/>{!socialImageAssetIdValid?<small role="alert">请输入合法的 asset_* 资产 ID。</small>:null}</label><label className="settings-wide">变更理由<input value={reason} onChange={event=>setReason(event.target.value)} maxLength={500}/></label></div><footer><span>{identity.state==="missing"?"首次保存将创建该 Locale 的共享内容版本。":"保存为该 Locale 的就绪共享内容草稿；公开站点仍需完成快照发布。"}</span><button onClick={saveIdentity} disabled={!csrfToken||siteName.trim().length<1||tagline.trim().length<1||!socialImageAssetIdValid}>保存设置草稿</button></footer></>:<div className="settings-empty"><WarningCircle size={22}/><p>当前没有可配置 Locale。</p></div>}</section>
      <aside className="panel locale-defaults"><header><GlobeHemisphereWest size={19}/><div><small>PUBLICATION DEFAULTS</small><strong>语言发布默认值</strong></div></header><div className="locale-default-lead"><span>{view.publicationDefaults.defaultLocale}</span><div><strong>默认 Locale</strong><small>回退内容不能满足发布就绪</small></div></div>{localeSetting?<div className="locale-settings-form"><label>文字方向<select value={direction} onChange={event=>setDirection(event.target.value as "ltr"|"rtl")}><option value="ltr">LTR</option><option value="rtl">RTL</option></select></label><label>回退 Locale<select value={isDefault?"":fallbackLocale} disabled={isDefault} onChange={event=>setFallbackLocale(event.target.value)}><option value="">无回退</option>{view.locales.filter(item=>item.locale!==localeSetting.locale).map(item=><option key={item.locale} value={item.locale}>{item.locale}</option>)}</select></label><label className="locale-check"><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/>启用</label><label className="locale-check"><input type="checkbox" checked={isDefault} onChange={event=>setIsDefault(event.target.checked)}/>设为默认</label><button disabled={!csrfToken||(localeSetting.isDefault&&(!enabled||!isDefault))} onClick={saveLocale}>保存 Locale 草稿</button></div>:null}<details className="locale-create"><summary>登记新 Locale</summary><div><label>BCP 47 标签<input value={newLocale} onChange={event=>setNewLocale(event.target.value)} maxLength={35} placeholder="例如 de 或 pt-BR"/></label><label>显示名称<input value={newLocaleName} onChange={event=>setNewLocaleName(event.target.value)} maxLength={100}/></label><label>文字方向<select value={newLocaleDirection} onChange={event=>setNewLocaleDirection(event.target.value as "ltr"|"rtl")}><option value="ltr">LTR</option><option value="rtl">RTL</option></select></label><label>初始回退<select value={newLocaleFallback} onChange={event=>setNewLocaleFallback(event.target.value)}>{view.locales.map(item=><option key={item.locale} value={item.locale}>{item.locale}</option>)}</select></label><button disabled={!csrfToken||!newLocaleValid||!newLocaleName.trim()} onClick={createLocale}>登记为草稿</button></div><small>标签必须是规范 BCP 47 值；新语言不会自动发布或生成内容。</small></details>{view.locales.map(item=><article key={item.locale}><span>{item.direction.toUpperCase()}</span><div><strong>{item.displayName}</strong><small>{item.locale} · {item.fallbackLocale?`回退 ${item.fallbackLocale}`:"无回退"}</small></div><b className={`state-${item.state}`}>{item.isDefault?"默认":item.enabled?"启用":"停用"}</b></article>)}<p>默认 Locale 不能停用或降级；回退内容不会被计为翻译完成。</p></aside>
    </div>
    <div className="settings-runtime-grid">
      <section className="panel infrastructure-card"><header><Cloud size={20}/><div><small>READ-ONLY INFRASTRUCTURE</small><strong>{view.infrastructure.deployment} · {view.infrastructure.region}</strong></div></header><div className="infra-facts"><article><span>Owner Access</span><b>密码认证</b></article><article><span>Cloudflare</span><b className={`state-${view.infrastructure.edge.cloudflare}`}>{stateLabel[view.infrastructure.edge.cloudflare]}</b></article><article><span>Nginx</span><b className={`state-${view.infrastructure.edge.nginx}`}>{stateLabel[view.infrastructure.edge.nginx]}</b></article><article><span>Scheduler</span><b className={`state-${view.infrastructure.scheduler.state}`}>{stateLabel[view.infrastructure.scheduler.state]}</b></article></div><div className="dependency-chips">{view.infrastructure.dependencies.map(item=><span key={item.id} className={`state-${item.state}`}>{item.id} · {stateLabel[item.state]}</span>)}</div></section>
      <section className="panel secrets-card"><header><Key size={20}/><div><small>SECRET PRESENCE</small><strong>仅显示配置状态</strong></div></header>{view.secretPresence.map(item=><article key={item.id}><span>{item.id.replaceAll("_"," ")}</span><b className={`state-${item.state}`}>{item.state==="configured"?<ShieldCheck size={15}/>:<WarningCircle size={15}/>} {stateLabel[item.state]}</b></article>)}<p>值、长度、指纹、来源和编辑入口均不会返回浏览器。</p></section>
    </div>
    <section className="panel recovery-deck"><header><div><small>KNOWN SNAPSHOT RECOVERY</small><strong>受限恢复工具</strong></div><span>r{view.infrastructure.snapshot.latestRevision??"—"} · {view.infrastructure.snapshot.affectedPathCount} 条已记录路径</span></header><div className="recovery-actions"><article><ArrowClockwise size={20}/><div><strong>重试发布确认</strong><p>仅在最新快照确认失败时可用。</p></div><b>{view.recovery.retryPublication.available?"在发布区执行":"当前不可用"}</b></article><article><Database size={20}/><div><strong>重建活动快照</strong><p>从当前已知活动快照创建新版本并重新确认。</p></div><button disabled={!view.recovery.rebuildSnapshot.available||confirmation!==view.infrastructure.deployment} onClick={()=>recover("recovery_rebuild")}>重建</button></article><article><HardDrives size={20}/><div><strong>刷新内容缓存</strong><p>仅重新确认活动快照已有的受影响路径。</p></div><button disabled={!view.recovery.invalidateContentCache.available||confirmation!==view.infrastructure.deployment} onClick={()=>recover("recovery_invalidate")}>刷新</button></article></div><div className="recovery-confirm"><label>输入部署 ID <code>{view.infrastructure.deployment}</code><input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><label>恢复理由<input value={reason} onChange={event=>setReason(event.target.value)} maxLength={500}/></label><span>{view.recovery.rollbackCandidates.length} 个已知回滚候选 · 回滚仍在发布区执行</span></div>{message?<p className="command-message" role="status">{message}</p>:null}</section>
  </section>;
}
