import type { Platform } from "@tikdd/contracts";

export const RESOLVE_POLL_INTERVAL_MS = 750;
export const RESOLVE_POLL_MAX_ATTEMPTS = 80;
export const RESOLVE_POLL_WINDOW_MS = RESOLVE_POLL_INTERVAL_MS * RESOLVE_POLL_MAX_ATTEMPTS;
export const YOUTUBE_RESOLVE_POLL_MAX_ATTEMPTS = 120;
export const YOUTUBE_RESOLVE_POLL_WINDOW_MS =
  RESOLVE_POLL_INTERVAL_MS * YOUTUBE_RESOLVE_POLL_MAX_ATTEMPTS;
export const DAILYMOTION_RESOLVE_POLL_MAX_ATTEMPTS = 260;
export const DAILYMOTION_RESOLVE_POLL_WINDOW_MS =
  RESOLVE_POLL_INTERVAL_MS * DAILYMOTION_RESOLVE_POLL_MAX_ATTEMPTS;

export function resolvePollMaxAttempts(platform: Platform): number {
  if (platform === "youtube") return YOUTUBE_RESOLVE_POLL_MAX_ATTEMPTS;
  if (platform === "dailymotion") return DAILYMOTION_RESOLVE_POLL_MAX_ATTEMPTS;
  return RESOLVE_POLL_MAX_ATTEMPTS;
}
