import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { AdminPasswordSchema, AdminSessionSchema, AdminSessionTokenSchema, AdminUsernameSchema, type AdminSession } from "@tikdd/admin-contracts";
import type { AdminAccountRecord, AdminAccountRepository } from "@tikdd/persistence";
import type Redis from "ioredis";

const prefix="tikdd:admin-auth:v1";const N=16384,r=8,p=1,keyLength=32;
function derive(password:string,salt:Buffer,length:number,options:{N:number;r:number;p:number}){return new Promise<Buffer>((resolve,reject)=>scryptCallback(password,salt,length,{...options,maxmem:64*1024*1024},(error,key)=>error?reject(error):resolve(key)));}
const commonPasswords=new Set(["passwordpassword","administrator","adminadminadmin","letmeinletmein","12345678901234","qwertyqwerty123"]);
const dummySalt=Buffer.from("TikDD-admin-auth-dummy-salt-v1");let dummyHash:Promise<Buffer>|null=null;
export interface AdminIdentity{subject:string;username:string;mode:"password"}
export interface AdminIdentityVerifier{verify(token:string|undefined):Promise<AdminIdentity>}
export class DevelopmentAdminIdentityVerifier implements AdminIdentityVerifier{constructor(private readonly subject:string){}async verify(){return{subject:this.subject,username:"development",mode:"password" as const};}}
export class AdminAuthenticationError extends Error{constructor(public readonly code:"INVALID_CREDENTIALS"|"RATE_LIMITED"|"UNAUTHORIZED"|"AUTH_UNAVAILABLE"="UNAUTHORIZED",public readonly retryAfterSeconds?:number){super("Admin authentication failed.");this.name="AdminAuthenticationError";}}

export function validateNewPassword(usernameInput:string,password:string){const username=AdminUsernameSchema.parse(usernameInput);AdminPasswordSchema.parse(password);if(!password.trim()||password.toLowerCase()===username||commonPasswords.has(password.toLowerCase()))throw new Error("Choose a stronger administrator password.");return password;}
export async function hashAdminPassword(username:string,password:string){validateNewPassword(username,password);const salt=randomBytes(16);const derived=await derive(password,salt,keyLength,{N,r,p});return `scrypt$v1$${N}$${r}$${p}$${salt.toString("base64url")}$${derived.toString("base64url")}`;}
export async function verifyAdminPassword(password:string,encoded:string|null){let expected:Buffer,salt:Buffer,costN=N,costR=r,costP=p;if(encoded){const parts=encoded.split("$");if(parts.length!==7||parts[0]!=="scrypt"||parts[1]!=="v1")encoded=null;else{costN=Number(parts[2]);costR=Number(parts[3]);costP=Number(parts[4]);salt=Buffer.from(parts[5]!,"base64url");expected=Buffer.from(parts[6]!,"base64url");}}
  if(!encoded){salt=dummySalt;dummyHash??=derive("not-the-administrator-password",salt,keyLength,{N,r,p});expected=await dummyHash;costN=N;costR=r;costP=p;}
  try{const actual=await derive(password,salt!,expected!.byteLength,{N:costN,r:costR,p:costP});return actual.byteLength===expected!.byteLength&&timingSafeEqual(actual,expected!);}catch{return false;}}
export function passwordHashNeedsUpgrade(encoded:string){const parts=encoded.split("$");return parts.length!==7||Number(parts[2])!==N||Number(parts[3])!==r||Number(parts[4])!==p;}

interface StoredSession{subject:string;username:string;credentialVersion:number;createdAt:string;lastSeenAt:string;expiresAt:string}
export class AdminPasswordAuthService implements AdminIdentityVerifier{
 constructor(private readonly accounts:AdminAccountRepository,private readonly redis:Redis,private readonly now=()=>new Date()){}
 private digest(value:string){return createHash("sha256").update(value).digest("hex");}private key(token:string){return `${prefix}:session:${this.digest(token)}`;}private accountSet(id:string){return `${prefix}:account:${id}:sessions`;}
 private rateKeys(username:string){const bucket=Math.floor(this.now().getTime()/900000);return{userKey:`${prefix}:login:user:${this.digest(username)}:${bucket}`,globalKey:`${prefix}:login:global:${bucket}`};}
 private async checkRateLimit(username:string){try{const{userKey,globalKey}=this.rateKeys(username);const[user,global]=await Promise.all([this.redis.get(userKey),this.redis.get(globalKey)]);if(Number(user??0)>=5||Number(global??0)>=50)throw new AdminAuthenticationError("RATE_LIMITED",900);}catch(cause){if(cause instanceof AdminAuthenticationError)throw cause;throw new AdminAuthenticationError("AUTH_UNAVAILABLE");}}
 private async recordFailure(username:string){try{const{userKey,globalKey}=this.rateKeys(username);const[user,global]=await Promise.all([this.redis.incr(userKey),this.redis.incr(globalKey)]);if(user===1)await this.redis.expire(userKey,900);if(global===1)await this.redis.expire(globalKey,900);}catch{throw new AdminAuthenticationError("AUTH_UNAVAILABLE");}}
 async login(usernameInput:string,password:string){let username:string;try{username=AdminUsernameSchema.parse(usernameInput);}catch{username="invalid-user";}await this.checkRateLimit(username);let account:AdminAccountRecord|null;try{account=await this.accounts.findByUsername(username);}catch{throw new AdminAuthenticationError("AUTH_UNAVAILABLE");}const valid=await verifyAdminPassword(password,account?.passwordHash??null);if(!account||!account.enabled||!valid){await this.recordFailure(username);throw new AdminAuthenticationError("INVALID_CREDENTIALS");}let effective=account;if(passwordHashNeedsUpgrade(account.passwordHash)){effective=await this.accounts.updatePassword(account.accountId,await hashAdminPassword(account.username,password))??account;}return this.createSession(effective);}
 private async createSession(account:AdminAccountRecord){const token=randomBytes(32).toString("base64url");const now=this.now();const expiresAt=new Date(now.getTime()+12*60*60*1000);const data:StoredSession={subject:account.accountId,username:account.username,credentialVersion:account.credentialVersion,createdAt:now.toISOString(),lastSeenAt:now.toISOString(),expiresAt:expiresAt.toISOString()};const key=this.key(token);await this.redis.set(key,JSON.stringify(data),"PX",30*60*1000);await this.redis.sadd(this.accountSet(account.accountId),key);await this.redis.expire(this.accountSet(account.accountId),12*60*60);return{sessionToken:AdminSessionTokenSchema.parse(token),session:AdminSessionSchema.parse({schemaVersion:"1",authenticated:true,subject:account.accountId,username:account.username,expiresAt:expiresAt.toISOString()})};}
 async verify(tokenInput:string|undefined):Promise<AdminIdentity>{const token=AdminSessionTokenSchema.safeParse(tokenInput);if(!token.success)throw new AdminAuthenticationError();let raw:string|null;try{raw=await this.redis.get(this.key(token.data));}catch{throw new AdminAuthenticationError("AUTH_UNAVAILABLE");}if(!raw)throw new AdminAuthenticationError();let stored:StoredSession;try{stored=JSON.parse(raw) as StoredSession;}catch{throw new AdminAuthenticationError();}const now=this.now();if(new Date(stored.expiresAt)<=now)throw new AdminAuthenticationError();const account=await this.accounts.findById(stored.subject);if(!account||!account.enabled||account.credentialVersion!==stored.credentialVersion)throw new AdminAuthenticationError();if(now.getTime()-new Date(stored.lastSeenAt).getTime()>=5*60*1000){stored.lastSeenAt=now.toISOString();const ttl=Math.min(30*60*1000,new Date(stored.expiresAt).getTime()-now.getTime());await this.redis.set(this.key(token.data),JSON.stringify(stored),"PX",ttl);}return{subject:account.accountId,username:account.username,mode:"password"};}
 async session(token:string):Promise<AdminSession>{const identity=await this.verify(token);const raw=await this.redis.get(this.key(token));const stored=JSON.parse(raw!) as StoredSession;return AdminSessionSchema.parse({schemaVersion:"1",authenticated:true,subject:identity.subject,username:identity.username,expiresAt:stored.expiresAt});}
 private async revokeAll(subject:string){const setKey=this.accountSet(subject);const keys=await this.redis.smembers(setKey);if(keys.length)await this.redis.del(...keys);await this.redis.del(setKey);}
 async logout(token:string|undefined,allDevices=false){if(!token)return;if(allDevices){const identity=await this.verify(token);await this.revokeAll(identity.subject);return;}await this.redis.del(this.key(token));}
 async changePassword(token:string,currentPassword:string,newPassword:string){const identity=await this.verify(token);const account=await this.accounts.findById(identity.subject);if(!account||!await verifyAdminPassword(currentPassword,account.passwordHash))throw new AdminAuthenticationError("INVALID_CREDENTIALS");const updated=await this.accounts.updatePassword(account.accountId,await hashAdminPassword(account.username,newPassword));if(!updated)throw new AdminAuthenticationError();await this.revokeAll(identity.subject);}
}
