import {
  qualifyFreeProviderCandidate,
  type FreeProviderCandidate,
  type FreeProviderQualificationResult
} from "./free-provider-qualification";

/**
 * Offline owner-supplied candidate matrix for Work Items 51, 56, 57 and 58. These records are intentionally
 * code-owned and do not make network calls, persist state, or grant rollout permission.
 * Work Items 59 and 60 add the third and fourth Instagram technical-validation batches.
 */
export const FREE_PROVIDER_PORTFOLIO: readonly FreeProviderCandidate[] = [
  {
    id: "tikvid",
    displayName: "TikVid.cc",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 1,
    failureFixtureCount: 4,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  },
  {
    id: "snapinsta",
    displayName: "SnapInsta.to",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 1,
    failureFixtureCount: 4,
    technicalState: "blocked",
    evidenceState: "canary-failed"
  },
  {
    id: "tokvid",
    displayName: "TokVid.io",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "tikcd",
    displayName: "TikCD.com",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: true,
    deliveryMode: "redirect",
    deliveryVerified: false,
    successFixtureCount: 2,
    failureFixtureCount: 4,
    technicalState: "resolved",
    evidenceState: "evaluating"
  },
  {
    id: "tikvid-io",
    displayName: "TikVid.io",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "gramsnap",
    displayName: "GramSnap",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "savevid",
    displayName: "SaveVid.net",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "fastdl",
    displayName: "FastDL.app",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "igram-world",
    displayName: "iGram.world",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "sssinstagram",
    displayName: "sssInstagram.com",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "inflact",
    displayName: "Inflact Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "savefrom-net",
    displayName: "SaveFrom.net Instagram Reels",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "collabstr",
    displayName: "Collabstr Instagram Reels",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "igexport",
    displayName: "IGExport",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "fastvideosave",
    displayName: "FastVideoSave",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "indown",
    displayName: "InDown",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "ahm7_alldl",
    displayName: "AHM7 AllDL",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "prexzy",
    displayName: "Prexzy APIs",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "resolved",
    evidenceState: "not-evaluated"
  },
  {
    id: "cliplatch",
    displayName: "ClipLatch",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "embedsocial-jp",
    displayName: "EmbedSocial.jp Instagram Reels Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "reelsvideo",
    displayName: "ReelsVideo.io",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "save-free",
    displayName: "Save-Free Reels Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "anonsaver",
    displayName: "AnonSaver",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "snap-insta",
    displayName: "Snap-Insta.to",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "dlreel",
    displayName: "DLReel",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "vidssave",
    displayName: "VidsSave Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "fdown-vn",
    displayName: "FDown.vn Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "downloadmedia-app",
    displayName: "DownloadMedia.app Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "bolta-ai",
    displayName: "Bolta AI Instagram Video Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  }
] as const;

export function qualifyFreeProviderPortfolio(): readonly FreeProviderQualificationResult[] {
  return FREE_PROVIDER_PORTFOLIO.map((candidate) => qualifyFreeProviderCandidate(candidate));
}
