import {
  qualifyFreeProviderCandidate,
  type FreeProviderCandidate,
  type FreeProviderQualificationResult
} from "./free-provider-qualification";

/**
 * Offline owner-supplied candidate matrix for Work Items 51, 56, 57, 58, 62, 64, 65 and 71. These records are intentionally
 * code-owned and do not make network calls, persist state, or grant rollout permission.
 * Work Items 59 through 61 add the later Instagram technical-validation batches and delivery-path evidence.
 */
export const FREE_PROVIDER_PORTFOLIO: readonly FreeProviderCandidate[] = [
  {
    id: "tikvid",
    displayName: "TikVid.cc",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 1,
    failureFixtureCount: 4,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  },
  {
    id: "snapinsta",
    displayName: "SnapInsta.to",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 1,
    failureFixtureCount: 4,
    technicalState: "blocked",
    evidenceState: "canary-failed"
  },
  {
    id: "tokvid",
    displayName: "TokVid.io",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "tikcd",
    displayName: "TikCD.com",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: true,
    deliveryMode: "redirect",
    deliveryVerified: false,
    successFixtureCount: 2,
    failureFixtureCount: 4,
    technicalState: "resolved",
    evidenceState: "evaluating"
  },
  {
    id: "tikvid-io",
    displayName: "TikVid.io",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "gramsnap",
    displayName: "GramSnap",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "savevid",
    displayName: "SaveVid.net",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "fastdl",
    displayName: "FastDL.app",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "igram-world",
    displayName: "iGram.world",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "sssinstagram",
    displayName: "sssInstagram.com",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "inflact",
    displayName: "Inflact Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "savefrom-net",
    displayName: "SaveFrom.net Instagram Reels",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "collabstr",
    displayName: "Collabstr Instagram Reels",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "igexport",
    displayName: "IGExport",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "fastvideosave",
    displayName: "FastVideoSave",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "indown",
    displayName: "InDown",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "ahm7_alldl",
    displayName: "AHM7 AllDL",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "prexzy",
    displayName: "Prexzy APIs",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "resolved",
    evidenceState: "evaluating"
  },
  {
    id: "cliplatch",
    displayName: "ClipLatch",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "resolved",
    evidenceState: "evaluating"
  },
  {
    id: "embedsocial-jp",
    displayName: "EmbedSocial.jp Instagram Reels Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "reelsvideo",
    displayName: "ReelsVideo.io",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "save-free",
    displayName: "Save-Free Reels Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "anonsaver",
    displayName: "AnonSaver",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "snap-insta",
    displayName: "Snap-Insta.to",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "dlreel",
    displayName: "DLReel",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "vidssave",
    displayName: "VidsSave Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "fdown-vn",
    displayName: "FDown.vn Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "downloadmedia-app",
    displayName: "DownloadMedia.app Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "bolta-ai",
    displayName: "Bolta AI Instagram Video Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "luxa",
    displayName: "Luxa Video Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "outfame",
    displayName: "Outfame Instagram Downloader",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "sssinsta-za",
    displayName: "SSSInsta.co.za",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "iqsaved",
    displayName: "IQSaved",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "cobalt-directory",
    displayName: "Cobalt Community Provider Pool",
    platforms: ["tiktok", "instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "tdownv4",
    displayName: "TikTok Downloader Worker v4",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "clipx",
    displayName: "ClipX Worker API",
    platforms: ["tiktok", "instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 0,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "postvault",
    displayName: "PostVault",
    platforms: ["tiktok", "instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "tikwm",
    displayName: "TikWM",
    platforms: ["tiktok"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "anydownloader",
    displayName: "AnyDownloader (self-hosted)",
    platforms: ["tiktok", "instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "not-tested",
    evidenceState: "not-evaluated"
  },
  {
    id: "reclip",
    displayName: "ReClip (self-hosted)",
    platforms: ["tiktok", "instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "not-tested",
    evidenceState: "not-evaluated"
  },
  {
    id: "fdown",
    displayName: "FDown.net",
    platforms: ["facebook"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "fdownloader-vn",
    displayName: "FDownloader.vn",
    platforms: ["facebook"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: true,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "fget",
    displayName: "FGet.io",
    platforms: ["facebook"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "instagram-video-downloader-vercel",
    displayName: "Instagram Video Downloader (Vercel)",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "reelsaver-fun",
    displayName: "ReelSaver.fun",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "no-media",
    evidenceState: "not-evaluated"
  },
  {
    id: "fdown-isuru",
    displayName: "FDown Isuru",
    platforms: ["facebook"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: true,
    deliveryMode: "redirect",
    deliveryVerified: false,
    successFixtureCount: 1,
    failureFixtureCount: 5,
    technicalState: "resolved",
    evidenceState: "evaluating"
  },
  {
    id: "vidown-netlify",
    displayName: "ViDown (Netlify)",
    platforms: ["instagram", "facebook"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "socialdownloader-space",
    displayName: "SocialDownloader.space",
    platforms: ["x", "instagram", "tiktok", "facebook", "youtube"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: true,
    deliveryMode: "redirect",
    deliveryVerified: false,
    successFixtureCount: 4,
    failureFixtureCount: 2,
    technicalState: "resolved",
    evidenceState: "evaluating"
  },
  {
    id: "social-media-downloader-eight",
    displayName: "Social Media Downloader (Vercel)",
    platforms: ["instagram", "tiktok", "facebook", "youtube"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: true,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "gram-grabberz",
    displayName: "Gram Grabberz",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "facebookone",
    displayName: "FacebookOne",
    platforms: ["facebook"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "not-evaluated"
  },
  {
    id: "reeldown",
    displayName: "ReelDown.io",
    platforms: ["instagram"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "reachable",
    evidenceState: "not-evaluated"
  },
  {
    id: "mediafetcher",
    displayName: "MediaFetcher.org",
    platforms: ["pinterest", "vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 2,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  },
  {
    id: "pinsaver",
    displayName: "PinSaver.online",
    platforms: ["pinterest"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 2,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  },
  {
    id: "pinterest-videodownloader",
    displayName: "Pinterest Video Downloader",
    platforms: ["pinterest"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: true,
    hostPolicyReviewed: true,
    deliveryMode: "redirect",
    deliveryVerified: false,
    successFixtureCount: 2,
    failureFixtureCount: 4,
    technicalState: "resolved",
    evidenceState: "evaluating"
  },
  {
    id: "hhhdownload",
    displayName: "hhhdownload.com",
    platforms: ["pinterest"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 1,
    failureFixtureCount: 1,
    technicalState: "resolved",
    evidenceState: "canary-failed"
  },
  {
    id: "clipsave",
    displayName: "ClipSave.org",
    platforms: ["vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  },
  {
    id: "tryunsora",
    displayName: "TryUnsora",
    platforms: ["vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: true,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "canary-failed"
  },
  {
    id: "whitehole",
    displayName: "WhiteHole.page",
    platforms: ["vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "canary-failed"
  },
  {
    id: "snapfetchr",
    displayName: "SnapFetchr",
    platforms: ["vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  },
  {
    id: "reelsdownloader-in",
    displayName: "ReelsDownloader.in",
    platforms: ["vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: true,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "blocked",
    evidenceState: "canary-failed"
  },
  {
    id: "savepanda",
    displayName: "SavePanda.io",
    platforms: ["vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  },
  {
    id: "snapvideo",
    displayName: "SnapVideo.cc",
    platforms: ["vimeo"],
    freeAccess: true,
    publicContentOnly: true,
    requiresLogin: false,
    requiresCookies: false,
    requiresInteractiveChallenge: false,
    requiresPaidApi: false,
    manifestReviewed: false,
    hostPolicyReviewed: false,
    deliveryMode: "resolution-only",
    deliveryVerified: false,
    successFixtureCount: 0,
    failureFixtureCount: 1,
    technicalState: "no-media",
    evidenceState: "canary-failed"
  }
] as const;

export function qualifyFreeProviderPortfolio(): readonly FreeProviderQualificationResult[] {
  return FREE_PROVIDER_PORTFOLIO.map((candidate) => qualifyFreeProviderCandidate(candidate));
}
