import Fastify from "fastify";
import {describe,expect,it} from "vitest";
import {registerPilotEvidenceDiagnostics} from "../src/pilot-evidence-diagnostics";

const token="pilot-evidence-token-with-at-least-32-characters";
const day={providerId:"ssstwitter",platform:"x",region:"global",observationClass:"public",utcDay:"2026-08-10",windowStartedAt:"2026-08-10T00:00:00.000Z",windowEndedAt:"2026-08-11T00:00:00.000Z",completeness:"sealed",aggregationVersion:1,taxonomyVersion:1,sourceWatermark:"2026-08-10T12:00:00.000Z",aggregateRevision:2,generatedAt:"2026-08-13T00:00:00.000Z",expiresAt:"2027-09-15T00:00:00.000Z",distinctResolutionTasks:12,resolutionObservationCount:12,resolutionSuccessCount:11,resolutionFailureCounts:{timeout:1},latencyHistogram:{"3000":12},latencyP50Ms:1500,latencyP95Ms:2500,fallbackDepthHistogram:{"0":10,"1":2},fallbackDepthP95:1,resultFormatCount:22,candidateCount:22,deliveryCounts:{"redirect_validation:passed":8},absoluteStopCount:0,lateAfterSealCount:0} as const;
function appWith(configured:string|null){const app=Fastify();registerPilotEvidenceDiagnostics(app,{token:configured,actorId:configured?"diagnostics.operator":null,store:{async listDailyEvidence(){return [day];},async latestEvaluatorRun(){return {status:"completed"};},async recordExport(){}},pilot:{async listActivePolicies(){return [];},async loadGuardSnapshot(){return {schemaVersion:"1",revision:0,generatedAt:new Date().toISOString(),guards:[]};}}});return app;}
const url="/internal/v1/pilot-evidence?providerId=ssstwitter&platform=x&region=global&observationClass=public&fromDay=2026-08-10&toDay=2026-08-10";
describe("pilot evidence diagnostics",()=>{
  it("is absent without its independent credential",async()=>{const app=appWith(null);try{expect((await app.inject({method:"GET",url})).statusCode).toBe(404);}finally{await app.close();}});
  it("returns aggregate-only no-store evidence",async()=>{const app=appWith(token);try{const response=await app.inject({method:"GET",url,headers:{authorization:`Bearer ${token}`}});expect(response.statusCode).toBe(200);expect(response.headers["cache-control"]).toBe("no-store");expect(response.json()).toMatchObject({scope:{providerId:"ssstwitter",observationClass:"public"},freshness:{completeness:"sealed"},sufficiency:{distinctSamples:12}});expect(response.body).not.toMatch(/taskId|candidateId|formatId|sourceUrl|targetUrl|ticket|cookie|header|payload|actorId/i);}finally{await app.close();}});
  it("exports only the requested class without a server artifact",async()=>{const app=appWith(token);try{const response=await app.inject({method:"GET",url:url.replace("pilot-evidence?","pilot-evidence/export?"),headers:{authorization:`Bearer ${token}`}});expect(response.statusCode).toBe(200);expect(response.headers["content-disposition"]).toContain("tikdd-evidence-2026-08-10-2026-08-10.json");expect(response.json()).toMatchObject({schemaVersion:"1",days:[{utcDay:"2026-08-10"}]});}finally{await app.close();}});
});
