import {
  AdminLocaleRevisionSchema,
  AdminPageRevisionSchema,
  AdminSharedContentRevisionSchema,
  type AdminLocaleDraftCommand,
  type AdminLocaleRevision,
  type AdminMutationReceipt,
  type AdminPageDraftCommand,
  type AdminPageRevision,
  type AdminSharedContentDraftCommand
} from "@tikdd/admin-contracts";
import type { Pool, PoolClient, QueryResultRow } from "pg";
import { AdminIdempotencyConflictError, AdminRoutePolicyConflictError, type RoutePolicyCommandIdentity } from "./admin-route-policy";

type Aggregate = "locale" | "page";
interface HeadRow extends QueryResultRow { head_revision: string; draft_revision: string | null; published_revision: string | null; }
interface ReceiptRow extends QueryResultRow { command_id:string; command_digest:Buffer; aggregate_kind:Aggregate; target_id:string; expected_revision:string|null; accepted_revision:string|null; current_revision:string|null; propagated_revision:string|null; state:AdminMutationReceipt["state"]; created_at:Date; completed_at:Date|null; }
interface LocaleRow extends QueryResultRow { locale_tag:string;revision:string;display_name:string;direction:"ltr"|"rtl";fallback_locale_tag:string|null;enabled:boolean;is_default:boolean;state:"draft"|"ready"|"published"|"archived";reason:string;actor_subject:string;created_at:Date; }
interface PageRow extends QueryResultRow { page_id:string;locale_tag:string;revision:string;page_type:"homepage"|"platform"|"guide"|"faq"|"legal";platform:string|null;state:"draft"|"ready"|"published"|"archived";content:unknown;seo:unknown;reason:string;actor_subject:string;created_at:Date; }
interface SharedRow extends QueryResultRow { locale_tag:string;revision:string;state:"draft"|"ready"|"published"|"archived";content:unknown;reason:string;actor_subject:string;created_at:Date; }

function locale(row:LocaleRow):AdminLocaleRevision{return AdminLocaleRevisionSchema.parse({schemaVersion:"1",locale:row.locale_tag,revision:Number(row.revision),displayName:row.display_name,direction:row.direction,fallbackLocale:row.fallback_locale_tag,enabled:row.enabled,isDefault:row.is_default,state:row.state,reason:row.reason,actorSubject:row.actor_subject,createdAt:row.created_at.toISOString()});}
function page(row:PageRow):AdminPageRevision{return AdminPageRevisionSchema.parse({schemaVersion:"1",pageId:row.page_id,locale:row.locale_tag,revision:Number(row.revision),pageType:row.page_type,platform:row.platform,state:row.state,content:row.content,seo:row.seo,reason:row.reason,actorSubject:row.actor_subject,createdAt:row.created_at.toISOString()});}
function shared(row:SharedRow){return AdminSharedContentRevisionSchema.parse({schemaVersion:"1",locale:row.locale_tag,revision:Number(row.revision),state:row.state,content:row.content,reason:row.reason,actorSubject:row.actor_subject,createdAt:row.created_at.toISOString()});}
function mapReceipt(row:ReceiptRow):AdminMutationReceipt{return {schemaVersion:"1",commandId:row.command_id,aggregate:row.aggregate_kind,targetId:row.target_id,expectedRevision:row.expected_revision===null?null:Number(row.expected_revision),acceptedRevision:row.accepted_revision===null?null:Number(row.accepted_revision),currentRevision:row.current_revision===null?null:Number(row.current_revision),propagatedRevision:row.propagated_revision===null?null:Number(row.propagated_revision),state:row.state,acceptedAt:row.created_at.toISOString(),completedAt:row.completed_at?.toISOString()??null};}
async function replay(client:PoolClient,identity:RoutePolicyCommandIdentity){const result=await client.query<ReceiptRow>(`SELECT command_id,command_digest,aggregate_kind,target_id,expected_revision::text,accepted_revision::text,current_revision::text,propagated_revision::text,state,created_at,completed_at FROM admin_command_receipts WHERE idempotency_digest=$1 AND expires_at>NOW() FOR UPDATE`,[identity.idempotencyDigest]);const row=result.rows[0];if(!row)return null;if(!row.command_digest.equals(identity.commandDigest))throw new AdminIdempotencyConflictError();return mapReceipt(row);}
async function receipt(client:PoolClient,input:{identity:RoutePolicyCommandIdentity;aggregate:Aggregate;targetId:string;expected:number|null;accepted:number|null;current:number|null}){const result=await client.query<ReceiptRow>(`INSERT INTO admin_command_receipts (command_id,idempotency_digest,command_digest,aggregate_kind,target_id,actor_subject,expected_revision,accepted_revision,current_revision,propagated_revision,state,completed_at,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,'propagated',NOW(),$10) RETURNING command_id,command_digest,aggregate_kind,target_id,expected_revision::text,accepted_revision::text,current_revision::text,propagated_revision::text,state,created_at,completed_at`,[input.identity.commandId,input.identity.idempotencyDigest,input.identity.commandDigest,input.aggregate,input.targetId,input.identity.actorSubject,input.expected,input.accepted,input.current,input.identity.expiresAt]);return mapReceipt(result.rows[0] as ReceiptRow);}
function expectHead(head:HeadRow|undefined,expected:number|null){if((head?Number(head.head_revision):null)!==expected)throw new AdminRoutePolicyConflictError();}

export class AdminContentManagementRepository {
  constructor(private readonly pool:Pool){}

  async listLocaleStates(){const result=await this.pool.query<LocaleRow&HeadRow>(`SELECT r.*,h.head_revision::text,h.draft_revision::text,h.published_revision::text FROM admin_locale_heads h JOIN admin_locale_revisions r ON r.locale_tag=h.locale_tag AND r.revision=ANY(ARRAY_REMOVE(ARRAY[h.draft_revision,h.published_revision],NULL)) ORDER BY r.is_default DESC,r.locale_tag,r.revision DESC`);const grouped=new Map<string,{headRevision:number;draft:AdminLocaleRevision|null;published:AdminLocaleRevision|null}>();for(const row of result.rows){const item=grouped.get(row.locale_tag)??{headRevision:Number(row.head_revision),draft:null,published:null};const value=locale(row);if(Number(row.draft_revision)===value.revision)item.draft=value;if(Number(row.published_revision)===value.revision)item.published=value;grouped.set(row.locale_tag,item);}return grouped;}
  async listAllPages(){const result=await this.pool.query<PageRow>(`SELECT r.* FROM admin_page_heads h JOIN admin_page_revisions r ON r.page_id=h.page_id AND r.locale_tag=h.locale_tag AND r.revision=COALESCE(h.draft_revision,h.published_revision) ORDER BY r.page_id,r.locale_tag`);return result.rows.map(page);}
  async listSharedContent(){const result=await this.pool.query<SharedRow>(`SELECT r.* FROM admin_shared_content_heads h JOIN admin_shared_content_revisions r ON r.locale_tag=h.locale_tag AND r.revision=COALESCE(h.draft_revision,h.published_revision) ORDER BY r.locale_tag`);return result.rows.map(shared);}

  async saveLocaleDraft(command:AdminLocaleDraftCommand,identity:RoutePolicyCommandIdentity){return this.tx(async client=>{const prior=await replay(client,identity);if(prior)return prior;const selected=await client.query<HeadRow>(`SELECT head_revision::text,draft_revision::text,published_revision::text FROM admin_locale_heads WHERE locale_tag=$1 FOR UPDATE`,[command.locale]);const current=selected.rows[0];expectHead(current,command.expectedRevision);const next=(current?Number(current.head_revision):0)+1;await client.query(`INSERT INTO admin_locale_revisions (locale_tag,revision,display_name,direction,fallback_locale_tag,enabled,is_default,state,reason,actor_subject) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[command.locale,next,command.displayName,command.direction,command.fallbackLocale,command.enabled,command.isDefault,command.state,command.reason,identity.actorSubject]);await client.query(`INSERT INTO admin_locale_heads(locale_tag,head_revision,draft_revision,published_revision) VALUES($1,$2,$2,NULL) ON CONFLICT(locale_tag) DO UPDATE SET head_revision=$2,draft_revision=$2,updated_at=NOW()`,[command.locale,next]);return receipt(client,{identity,aggregate:"locale",targetId:command.locale,expected:command.expectedRevision,accepted:next,current:next});});}
  async discardLocale(command:{locale:string;expectedRevision:number;draftRevision:number},identity:RoutePolicyCommandIdentity){return this.discard("locale",command.locale,command.expectedRevision,command.draftRevision,identity);}

  async savePageDraft(command:AdminPageDraftCommand,identity:RoutePolicyCommandIdentity){return this.tx(async client=>{const prior=await replay(client,identity);if(prior)return prior;const selected=await client.query<HeadRow>(`SELECT head_revision::text,draft_revision::text,published_revision::text FROM admin_page_heads WHERE page_id=$1 AND locale_tag=$2 FOR UPDATE`,[command.pageId,command.locale]);const current=selected.rows[0];expectHead(current,command.expectedRevision);const next=(current?Number(current.head_revision):0)+1;await client.query(`INSERT INTO admin_page_revisions(page_id,locale_tag,revision,page_type,platform,state,content,seo,reason,actor_subject) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10)`,[command.pageId,command.locale,next,command.pageType,command.platform,command.state,JSON.stringify(command.content),JSON.stringify(command.seo),command.reason,identity.actorSubject]);await client.query(`INSERT INTO admin_page_heads(page_id,locale_tag,head_revision,draft_revision,published_revision) VALUES($1,$2,$3,$3,NULL) ON CONFLICT(page_id,locale_tag) DO UPDATE SET head_revision=$3,draft_revision=$3,updated_at=NOW()`,[command.pageId,command.locale,next]);return receipt(client,{identity,aggregate:"page",targetId:`${command.pageId}/${command.locale}`,expected:command.expectedRevision,accepted:next,current:next});});}
  async discardPage(command:{pageId:string;locale:string;expectedRevision:number;draftRevision:number},identity:RoutePolicyCommandIdentity){return this.discard("page",`${command.pageId}/${command.locale}`,command.expectedRevision,command.draftRevision,identity,command.pageId,command.locale);}

  async saveSharedDraft(command:AdminSharedContentDraftCommand,identity:RoutePolicyCommandIdentity){return this.tx(async client=>{const prior=await replay(client,identity);if(prior)return prior;const selected=await client.query<HeadRow>(`SELECT head_revision::text,draft_revision::text,published_revision::text FROM admin_shared_content_heads WHERE locale_tag=$1 FOR UPDATE`,[command.locale]);const current=selected.rows[0];expectHead(current,command.expectedRevision);const next=(current?Number(current.head_revision):0)+1;await client.query(`INSERT INTO admin_shared_content_revisions(locale_tag,revision,state,content,reason,actor_subject) VALUES($1,$2,$3,$4::jsonb,$5,$6)`,[command.locale,next,command.state,JSON.stringify(command.content),command.reason,identity.actorSubject]);await client.query(`INSERT INTO admin_shared_content_heads(locale_tag,head_revision,draft_revision,published_revision) VALUES($1,$2,$2,NULL) ON CONFLICT(locale_tag) DO UPDATE SET head_revision=$2,draft_revision=$2,updated_at=NOW()`,[command.locale,next]);return receipt(client,{identity,aggregate:"page",targetId:`shared/${command.locale}`,expected:command.expectedRevision,accepted:next,current:next});});}

  private async discard(aggregate:Aggregate,targetId:string,expected:number,draftRevision:number,identity:RoutePolicyCommandIdentity,pageId?:string,localeTag?:string){return this.tx(async client=>{const table=aggregate==="locale"?"admin_locale_heads":"admin_page_heads";const where=aggregate==="locale"?"locale_tag=$1":"page_id=$1 AND locale_tag=$2";const params=aggregate==="locale"?[targetId]:[pageId,localeTag];const selected=await client.query<HeadRow>(`SELECT head_revision::text,draft_revision::text,published_revision::text FROM ${table} WHERE ${where} FOR UPDATE`,params);const current=selected.rows[0];expectHead(current,expected);if(!current||Number(current.draft_revision)!==draftRevision)throw new AdminRoutePolicyConflictError();await client.query(`UPDATE ${table} SET draft_revision=NULL,updated_at=NOW() WHERE ${where}`,params);const published=current.published_revision===null?null:Number(current.published_revision);return receipt(client,{identity,aggregate,targetId,expected,accepted:null,current:published});});}
  private async tx<T>(run:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");const value=await run(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
}

