import { createHash } from "node:crypto";
import {
  AdminMutationReceiptSchema,
  PublishedContentSnapshotSchema,
  type AdminContentPublishCommand,
  type AdminContentRollbackCommand,
  type AdminContentRetryPropagationCommand,
  type AdminMutationReceipt,
  type PublishedContentSnapshot
} from "@tikdd/admin-contracts";
import type { Pool, PoolClient, QueryResultRow } from "pg";
import { AdminIdempotencyConflictError, AdminRoutePolicyConflictError, type RoutePolicyCommandIdentity } from "./admin-route-policy";

export interface AdminPublishedSnapshotRow extends QueryResultRow {
  snapshot_id:string; deployment:string; revision:string; previous_snapshot_id:string|null;
  content_hash:string; payload:unknown;
  propagation_state:"accepted"|"propagating"|"propagated"|"propagation_failed"|"rolled_back";
  affected_paths:unknown; created_at:Date; propagated_at:Date|null;
}
interface ReceiptRow extends QueryResultRow { command_id:string;command_digest:Buffer;aggregate_kind:"snapshot";target_id:string;expected_revision:string|null;accepted_revision:string|null;current_revision:string|null;propagated_revision:string|null;state:AdminMutationReceipt["state"];created_at:Date;completed_at:Date|null; }
function mapReceipt(row:ReceiptRow){return AdminMutationReceiptSchema.parse({schemaVersion:"1",commandId:row.command_id,aggregate:"snapshot",targetId:row.target_id,expectedRevision:row.expected_revision===null?null:Number(row.expected_revision),acceptedRevision:row.accepted_revision===null?null:Number(row.accepted_revision),currentRevision:row.current_revision===null?null:Number(row.current_revision),propagatedRevision:row.propagated_revision===null?null:Number(row.propagated_revision),state:row.state,acceptedAt:row.created_at.toISOString(),completedAt:row.completed_at?.toISOString()??null});}
async function replay(client:PoolClient,identity:RoutePolicyCommandIdentity){const result=await client.query<ReceiptRow>(`SELECT command_id,command_digest,aggregate_kind,target_id,expected_revision::text,accepted_revision::text,current_revision::text,propagated_revision::text,state,created_at,completed_at FROM admin_command_receipts WHERE idempotency_digest=$1 AND expires_at>NOW() FOR UPDATE`,[identity.idempotencyDigest]);const row=result.rows[0];if(!row)return null;if(!row.command_digest.equals(identity.commandDigest))throw new AdminIdempotencyConflictError();return mapReceipt(row);}
async function lockDeployment(client:PoolClient,deployment:string){await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[deployment]);}
async function latest(client:PoolClient,deployment:string){return (await client.query<AdminPublishedSnapshotRow>(`SELECT snapshot_id,deployment,revision::text,previous_snapshot_id,content_hash,payload,propagation_state,affected_paths,created_at,propagated_at FROM admin_published_snapshots WHERE deployment=$1 ORDER BY revision DESC LIMIT 1`,[deployment])).rows[0];}
function expectRevision(current:AdminPublishedSnapshotRow|undefined,expected:number|null){if((current?Number(current.revision):null)!==expected)throw new AdminRoutePolicyConflictError();}
async function receipt(client:PoolClient,input:{identity:RoutePolicyCommandIdentity;deployment:string;expected:number|null;accepted:number;state:"propagating"|"propagated"|"propagation_failed";propagated:number|null}){const done=input.state!=="propagating";const result=await client.query<ReceiptRow>(`INSERT INTO admin_command_receipts(command_id,idempotency_digest,command_digest,aggregate_kind,target_id,actor_subject,expected_revision,accepted_revision,current_revision,propagated_revision,state,completed_at,expires_at) VALUES($1,$2,$3,'snapshot',$4,$5,$6,$7,$7,$8,$9,CASE WHEN $10 THEN NOW() ELSE NULL END,$11) RETURNING command_id,command_digest,aggregate_kind,target_id,expected_revision::text,accepted_revision::text,current_revision::text,propagated_revision::text,state,created_at,completed_at`,[input.identity.commandId,input.identity.idempotencyDigest,input.identity.commandDigest,input.deployment,input.identity.actorSubject,input.expected,input.accepted,input.propagated,input.state,done,input.identity.expiresAt]);return mapReceipt(result.rows[0] as ReceiptRow);}

export class AdminContentPublicationRepository {
  constructor(private readonly pool:Pool){}
  async getActive(deployment:string){const result=await this.pool.query<AdminPublishedSnapshotRow>(`SELECT s.snapshot_id,s.deployment,s.revision::text,s.previous_snapshot_id,s.content_hash,s.payload,s.propagation_state,s.affected_paths,s.created_at,s.propagated_at FROM admin_published_snapshot_heads h JOIN admin_published_snapshots s ON s.snapshot_id=h.active_snapshot_id WHERE h.deployment=$1`,[deployment]);return result.rows[0]??null;}
  async getLatest(deployment:string){return (await this.pool.query<AdminPublishedSnapshotRow>(`SELECT snapshot_id,deployment,revision::text,previous_snapshot_id,content_hash,payload,propagation_state,affected_paths,created_at,propagated_at FROM admin_published_snapshots WHERE deployment=$1 ORDER BY revision DESC LIMIT 1`,[deployment])).rows[0]??null;}
  async listRecent(deployment:string,limit=10){return (await this.pool.query<AdminPublishedSnapshotRow>(`SELECT snapshot_id,deployment,revision::text,previous_snapshot_id,content_hash,payload,propagation_state,affected_paths,created_at,propagated_at FROM admin_published_snapshots WHERE deployment=$1 ORDER BY revision DESC LIMIT $2`,[deployment,limit])).rows;}
  async publish(command:AdminContentPublishCommand,snapshot:PublishedContentSnapshot,paths:string[],identity:RoutePolicyCommandIdentity){return this.tx(async client=>{const prior=await replay(client,identity);if(prior)return prior;await lockDeployment(client,command.deployment);const current=await latest(client,command.deployment);expectRevision(current,command.expectedRevision);const next=(current?Number(current.revision):0)+1;const active=(await client.query<{active_snapshot_id:string}>(`SELECT active_snapshot_id FROM admin_published_snapshot_heads WHERE deployment=$1`,[command.deployment])).rows[0];if(snapshot.revision!==next||snapshot.previousSnapshotId!==(active?.active_snapshot_id??null))throw new AdminRoutePolicyConflictError();const validated=PublishedContentSnapshotSchema.parse(snapshot);await client.query(`INSERT INTO admin_published_snapshots(snapshot_id,deployment,revision,previous_snapshot_id,schema_version,content_hash,payload,propagation_state,reason,actor_subject,affected_paths) VALUES($1,$2,$3,$4,'1',$5,$6::jsonb,'propagating',$7,$8,$9::jsonb)`,[validated.snapshotId,command.deployment,next,validated.previousSnapshotId,validated.contentHash,JSON.stringify(validated),command.reason,identity.actorSubject,JSON.stringify(paths)]);
    await client.query(`UPDATE admin_locale_revisions r SET state='published' FROM admin_locale_heads h WHERE r.locale_tag=h.locale_tag AND r.revision=h.draft_revision AND r.state='ready'`);
    await client.query(`UPDATE admin_locale_heads h SET published_revision=draft_revision,draft_revision=NULL,updated_at=NOW() WHERE draft_revision IS NOT NULL AND EXISTS(SELECT 1 FROM admin_locale_revisions r WHERE r.locale_tag=h.locale_tag AND r.revision=h.draft_revision AND r.state='published')`);
    await client.query(`UPDATE admin_page_revisions r SET state='published' FROM admin_page_heads h WHERE r.page_id=h.page_id AND r.locale_tag=h.locale_tag AND r.revision=h.draft_revision AND r.state='ready'`);
    await client.query(`UPDATE admin_page_heads h SET published_revision=draft_revision,draft_revision=NULL,updated_at=NOW() WHERE draft_revision IS NOT NULL AND EXISTS(SELECT 1 FROM admin_page_revisions r WHERE r.page_id=h.page_id AND r.locale_tag=h.locale_tag AND r.revision=h.draft_revision AND r.state='published')`);
    await client.query(`UPDATE admin_shared_content_revisions r SET state='published' FROM admin_shared_content_heads h WHERE r.locale_tag=h.locale_tag AND r.revision=h.draft_revision AND r.state='ready'`);
    await client.query(`UPDATE admin_shared_content_heads h SET published_revision=draft_revision,draft_revision=NULL,updated_at=NOW() WHERE draft_revision IS NOT NULL AND EXISTS(SELECT 1 FROM admin_shared_content_revisions r WHERE r.locale_tag=h.locale_tag AND r.revision=h.draft_revision AND r.state='published')`);
    return receipt(client,{identity,deployment:command.deployment,expected:command.expectedRevision,accepted:next,state:"propagating",propagated:null});});}
  async completePropagation(snapshotId:string,commandId:string,success:boolean):Promise<AdminMutationReceipt>{return this.tx(async client=>{const found=(await client.query<AdminPublishedSnapshotRow>(`SELECT snapshot_id,deployment,revision::text,previous_snapshot_id,content_hash,payload,propagation_state,affected_paths,created_at,propagated_at FROM admin_published_snapshots WHERE snapshot_id=$1 FOR UPDATE`,[snapshotId])).rows[0];if(!found)throw new Error("Published snapshot is unavailable.");await lockDeployment(client,found.deployment);const state=success?"propagated":"propagation_failed";await client.query(`UPDATE admin_published_snapshots SET propagation_state=$2,propagated_at=CASE WHEN $2='propagated' THEN NOW() ELSE propagated_at END,revalidation_attempts=revalidation_attempts+1 WHERE snapshot_id=$1`,[snapshotId,state]);if(success){const current=(await client.query<{active_snapshot_id:string}>(`SELECT active_snapshot_id FROM admin_published_snapshot_heads WHERE deployment=$1`,[found.deployment])).rows[0];await client.query(`INSERT INTO admin_published_snapshot_heads(deployment,revision,active_snapshot_id,previous_snapshot_id) VALUES($1,$2,$3,$4) ON CONFLICT(deployment) DO UPDATE SET revision=$2,active_snapshot_id=$3,previous_snapshot_id=$4,updated_at=NOW()`,[found.deployment,Number(found.revision),snapshotId,current?.active_snapshot_id??null]);}const result=await client.query<ReceiptRow>(`UPDATE admin_command_receipts SET state=$2,propagated_revision=CASE WHEN $2='propagated' THEN accepted_revision ELSE NULL END,completed_at=NOW() WHERE command_id=$1 RETURNING command_id,command_digest,aggregate_kind,target_id,expected_revision::text,accepted_revision::text,current_revision::text,propagated_revision::text,state,created_at,completed_at`,[commandId,state]);return mapReceipt(result.rows[0] as ReceiptRow);});}
  async rollback(command:AdminContentRollbackCommand,identity:RoutePolicyCommandIdentity){return this.tx(async client=>{const prior=await replay(client,identity);if(prior)return prior;await lockDeployment(client,command.deployment);const current=await latest(client,command.deployment);expectRevision(current,command.expectedRevision);const selected=(await client.query<AdminPublishedSnapshotRow>(`SELECT snapshot_id,deployment,revision::text,previous_snapshot_id,content_hash,payload,propagation_state,affected_paths,created_at,propagated_at FROM admin_published_snapshots WHERE deployment=$1 AND revision=$2 AND propagation_state='propagated' FOR SHARE`,[command.deployment,command.targetRevision])).rows[0];if(!selected||!current)throw new AdminRoutePolicyConflictError();const active=(await client.query<{active_snapshot_id:string}>(`SELECT active_snapshot_id FROM admin_published_snapshot_heads WHERE deployment=$1`,[command.deployment])).rows[0];const source=PublishedContentSnapshotSchema.parse(selected.payload);const next=Number(current.revision)+1;const snapshotId=`snap_${createHash("md5").update(`${command.deployment}:${next}:${source.contentHash}`).digest("hex")}`;const payload=PublishedContentSnapshotSchema.parse({...source,snapshotId,revision:next,previousSnapshotId:active?.active_snapshot_id??null,generatedAt:new Date().toISOString()});await client.query(`INSERT INTO admin_published_snapshots(snapshot_id,deployment,revision,previous_snapshot_id,schema_version,content_hash,payload,propagation_state,reason,actor_subject,affected_paths) VALUES($1,$2,$3,$4,'1',$5,$6::jsonb,'propagating',$7,$8,$9::jsonb)`,[snapshotId,command.deployment,next,payload.previousSnapshotId,payload.contentHash,JSON.stringify(payload),command.reason,identity.actorSubject,JSON.stringify(selected.affected_paths)]);return receipt(client,{identity,deployment:command.deployment,expected:command.expectedRevision,accepted:next,state:"propagating",propagated:null});});}
  async markPropagation(command:AdminContentRetryPropagationCommand,success:boolean,identity:RoutePolicyCommandIdentity){return this.tx(async client=>{const prior=await replay(client,identity);if(prior)return prior;await lockDeployment(client,command.deployment);const current=await latest(client,command.deployment);expectRevision(current,command.expectedRevision);if(current?.snapshot_id!==command.snapshotId||current.propagation_state!=="propagation_failed")throw new AdminRoutePolicyConflictError();const accepted=await receipt(client,{identity,deployment:command.deployment,expected:command.expectedRevision,accepted:command.expectedRevision,state:"propagating",propagated:null});return accepted;}).then(async accepted=>this.completePropagation(command.snapshotId,accepted.commandId,success));}
  private async tx<T>(run:(client:PoolClient)=>Promise<T>){const client=await this.pool.connect();try{await client.query("BEGIN");const value=await run(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
}
